### ISSUE TITLE
Unable to run RFuzz

### ISSUE THREAD

**Issue by animeshbchowdhury** [ekiwi/rfuzz#1]
Hi,

I am trying to run RFuzz at my end on Ubuntu 18.04 LTS version. I have gone through the README.md file, installed all the required dependencies.

Finally, I am trying to run :  `make run`.

I encountered an error which is shown below :

![error1](https://user-images.githubusercontent.com/11498919/61288657-3cbed700-a7e5-11e9-8203-e9c75ae873e5.png)

I analysed the file `meson.build` in the folder `verilator` and suspected that at line number 49, that verilator_src might be of type non-array object (I am not sure as I have never used meson before ! ) Based on the comment, which you have put up, I think it would be verilator_files[0] & verilator_files[1] instead on  verilator_src[0] and verilator_src[1].

Can you please help me with this issue ?

**Comment by ekiwi** [comment]
Thanks for trying out `rfuzz`.

In the output that you posted it says that your `meson` version is `0.29.0`.
Could it be that you are running on Ubuntu 16.04?
The `meson` version provided with Ubuntu 18.04 should be `0.45.1`.
See: https://packages.ubuntu.com/search?keywords=meson

**Comment by animeshbchowdhury** [comment]
I upgraded from Ubuntu 16.04 to 18.04 LTS from system. While upgrade, I kept certain package version intact for backward compatibility dependency for other tools. I will try it on a fresh installation of Ubuntu 18.04 and see if the issue persists or not.

Thanks for the prompt help!

**Comment by ekiwi** [comment]
> Thanks for the prompt help!

No problem!

If you are concerned about your other tools, you could also setup a Ubuntu 18.04 LTS in [VirtualBox](https://www.virtualbox.org/), either manually or using vagrant and the provided [Vagrantfile](https://github.com/ekiwi/rfuzz/blob/master/Vagrantfile).
