### ISSUE TITLE
try to use rfuzz

### ISSUE THREAD

**Issue by aabdelsa** [ekiwi/rfuzz#3]
Hello, i am trying to use rfuzz to generate workload for some architectures. some of my architecture are combinational designs. so there is no need for concatenating the inputs through time. i see that the number of test input bits is fixed to 35 bytes. i need to change it according to the design. so how could i do that ?
also there is something printed in the screen (of fuzzer) called " Bitmap " and it have some values. i am not sure what this " Bitmap" means. I understand that if i have inputs (a(8 bits) , b(16 bits), c(1 bit)) and i want to use them. I need to assign first 8 bits to a then next 16 bits to b then 1 bit to c then next cycle use next 8 bits to a etc. am i right ?

**Comment by ekiwi** [comment]
>  i see that the number of test input bits is fixed to 35 bytes. i need to change it according to the design. so how could i do that ?

The number of bytes per cycle is determined by the size of your input wires.
If you want the fuzzer to only fuzz for one cycle try using this option:
```
--seed-cycles <seed_cycles>     The starting seed consits of all zeros for N cycles. [default: 5]
```



> also there is something printed in the screen (of fuzzer) called " Bitmap " and it have some values. i am not sure what this " Bitmap" means

The "bitmap" keeps track of which mux control inputs have been toggled. It is updated in [analyze_coverage](https://github.com/ekiwi/rfuzz/blob/40080ec21d57950719a692c336acc75af418d70a/fuzzer/src/analysis.rs#L223)

**Comment by aabdelsa** [comment]
hello, thanks for your reply. i don't know how to use this option. when i try to use 
kfuzz [FLAGS] [OPTIONS] <TOML> --output-directory <DIR>
it gives me error ( command kfuzz not found ). 
also when i try to use rfuzz to generate inputs for small RISK machine it gives me a very small input set ( 9 files ) and most of them are zeros. i want to have a bigger set of inputs which contains numbers. if i use this set i will find myself testing zeros most of the cycles. is there any way to change it ?

**Comment by aabdelsa** [comment]
what make it decide to stop adding new inputs to S ? i see that number of files (entry) is constant after a while. but the fuzzing is still running ! i don't understand what makes it think this is enough input cases ?

**Comment by aabdelsa** [comment]
also want to know how to create log file. sorry for a lot of questions
