### ISSUE TITLE
Test with RocketTile

### ISSUE THREAD

**Issue by JaewonHur** [ekiwi/rfuzz#4]
Hi.
Recently I'm trying rfuzz to test Rocket chip designs. (with verilator software simulation)

I followed the instructions in README.
However, it takes long time to simulate RocketTile, approximately 100 cycles per second.

 Is there any way to accelerate the simulation speed?

**Comment by ekiwi** [comment]
> Is there any way to accelerate the simulation speed?

Sorry for the late reply. The way you can speed up fuzzing is to use firsim on an FPGA. Unfortunately, that part of the code is the hardest to setup.
