### ISSUE TITLE
Need help with Rfuzz inputs

### ISSUE THREAD

**Issue by Rahul-Kande** [ekiwi/rfuzz#5]
Hi, 

I want to compare the output of rocket-chip when fuzzed with Rfuzz with SPIKE, the ISA simulator. For this, I will have to run the spike with the same inputs as the ones used on rocket-chip. In the repository where can I find the elf or binary files used as input to drive the rocket-chip? Are they output in a format that SPIKE can accept directly or does the input generated by Rfuzz have to be modified to use with SPIKE? 

Any help regarding this task would be really helpful. 

Thanking you in advance.

**Comment by ekiwi** [comment]
If you are interested in fuzzing RISC-V processors in particular and to compare their execution to a software model, I would advise you to look into Difuzz. It is really cool work that makes the fuzzing idea much more practical for the purpose of processor testing. The [paper](https://compsec.snu.ac.kr/papers/hur-difuzzrtl.pdf) shows how they found a bunch of bugs in open source RISC-V processors and [their implementation](https://github.com/compsec-snu/difuzz-rtl) might help you with the fuzzing setup you are asking about.

I hope this helps!
